---
title: "Oklahoma Earthquakes and Saltwater Injection Wells"
author: "Andrewdnolan"
date: "4/12/2019"
output:
  pdf_document: default
  html_document: default
---

This is an [Kaggle dataset](https://www.kaggle.com/ksuchris2000/oklahoma-earthquakes-and-saltwater-injection-wells). 

```{r, message=FALSE}
library(tidyverse)

well_df <- read_csv('data/InjectionWells_w_geology.csv')
wells <- well_df %>% filter(LONG > -140 & LONG < -50) 

quake_df <- read_csv('data/okQuakes_w_geology.csv')
quakes <- quake_df %>% drop_na(mag, STATE) 

```

```{r, message=FALSE}
library(maps)
library(mapdata)
library(ggthemes)

roi <- map_data('county') %>%
    as.data.frame() %>%
    filter(region == 'oklahoma' )

wells %>% 
  mutate(subregion = tolower(County)) %>% 
  group_by(subregion) %>% 
  summarize(n_wells = n()) %>% 
  right_join(roi, by = c('subregion')) %>%
  ggplot(aes(x=long, y = lat, group = group, fill = n_wells)) +
  geom_polygon() + 
  geom_path(color = 'white', size = 0.1) + 
  scale_fill_continuous(low = "orange", 
                          high = "darkred",
                          name = 'Injection Wells \nper county', 
                        trans = "log10") +
  theme_map() + 
  coord_map('albers', lat0=30, lat1=40) +
  ggtitle("Saltwater injection well per county") +
  theme(plot.title = element_text(hjust = 0.5))

```


```{r}
roi2 <- map_data('state', c('oklahoma', 'texas', 'new mexico', 'kansas', 'colorado', 'missouri', 'arkansas', 'louisiana')) %>%
    as.data.frame() 

quakes$region <- map_chr(quakes$STATE, function(x) { tolower(state.name[grep(x, state.abb)]) })

quakes %>% filter(mag > 2.5) %>% 
  select(region) %>% group_by(region) %>% 
  summarise(n_quakes = n()) %>% right_join(roi2, by = c('region')) %>% 
  ggplot(aes(x = long, y = lat, group = group, fill = n_quakes)) + geom_polygon() + 
    geom_path(color = 'white', size = 0.1) + 
    scale_fill_continuous(low = "orange", 
                          high = "darkred",
                          name = 'Number of Quakes') + 
  theme_map() + 
  coord_map('albers', lat0=30, lat1=40) 

```


```{r}
#library(lubridate)

ggplot(data = quake_df) +
  geom_bar( mapping = aes(x = year(time), y = floor(mag)), stat="identity" , fill = 'orange') +
  coord_flip() + 
  labs(x = '', y = 'Number of Quakes', title = 'Greater Oklahoma Area Quakes by from 1977 to 2015')
```

```{r}
library(geosphere)
library(lubridate)
quakes_sub <- quakes[1:200,]
wells_sub <- wells[1:200, ]
wells_sub$`Approval Date` <- mdy(wells_sub$`Approval Date`)

well_geology <- paste('well',names(wells_sub)[24:30], sep = "_")
well_info <- names(wells_sub)[c(5, 9, 10, 17, 18)]
quakes_sub[,c(well_info, well_geology)] = NA

nearest_well <- function(row,well_df){
  print(row)
  # active_wells <- well_df %>% filter(`Approval Date`< row[9])
  # dist_vec <- distHaversine(c(row[16], row[15]), active_wells %>% select(LONG, LAT))
  # row[,31:43] <- active_wells[which.min(dist_vec), c(5, 9, 10, 17, 18, 24:30)]
}



active_wells <- wells_sub %>% filter(`Approval Date`< quakes_sub$time[1])
dist_vec <- distHaversine(c(quakes_sub$longitude[1], quakes_sub$latitude[1]), active_wells %>% select(LONG, LAT))
quakes_sub[,31:43] <- active_wells[which.min(dist_vec), c(5, 9, 10, 17, 18, 24:30)]


```
[help with maps](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html)

[idea for the maps / plots to make](https://www.kaggle.com/captcalculator/wildfire-exploratory-analysis)

[USGS maps source](https://mrdata.usgs.gov/geology/state/)

[USGS geophysical data](https://mrdata.usgs.gov/airborne/map-us.html)

[giffs](https://ryanpeek.github.io/2016-10-19-animated-gif_maps_in_R/)

[efficent searching in dataframe](geopandas.org/reference/geopandas.overlay.html)

[distance opperations](https://stackoverflow.com/questions/31668163/geographic-geospatial-distance-between-2-lists-of-lat-lon-points-coordinates)


